### ISSUE TITLE
Crashing when creating a new client 1.7

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3748]
## 💥 Crash Report

Create a new project and create a new client through either new entry or editing an existing.

Start a new entry or edit an existing entry, type a new project name and create a new project, then type a new client name and create a new client. The app will crash.
On inspection later it appears that the client was created, but the project wasn't during this process.
### 👥 Impact

This occurs everytime I attempt to create a new client.
### 📝  Exception & Stack Trace
`Exception type and message`
```cs
Stacktrace
```

**Comment by ApocalypticFish** [comment]
It also occurs if you enter a description, add a project name and click no project

**Comment by amulware** [comment]
This issue lacks information in the description and it is unclear whether it was addressed with the referenced pull request or not.

**Comment by amulware** [comment]
Please use the bug report issue template unless you have the actual technical information for the rest of the description.

**Comment by heytherewill** [comment]
@daividssilverio Was this fixed by #3751 or is it still happening?

**Comment by daividssilverio** [comment]
Yeah, it should have been fixed by #3751. But it seems @ApocalypticFish was able to replicate this again once while testing 1.9. Leave it open for now, I'll take a look into this again.

**Comment by juanlaube** [comment]
I can't reproduce this issue.

**Comment by ApocalypticFish** [comment]
I had it happen once during testing of 1.9 but I wasn't able to replicate it afterwards. I'm still not convinced that this is fully resolved.
The conditions were
Clean install (cleared cache and app data)
Signed up with new account
Started new time entry
Entered description
Created new project successfully
Created new client successfully
Entered new tag name then when I attempted to create tag the app crashed.
I'm not sure if this was a connection related but it might be worth checking on a flaky connection.
This issue or one very much like it has been happening I think since even before 1.7 but it's so intermittent I'm not sure if we've ever fixed it but it still pops up from time to time in testing.

**Comment by juanlaube** [comment]
I'm still unable to reproduce this with that information. However considering this happened not only with clients, but also tags, I'm just thinking this could be related to #3730.

**Comment by dshr** [comment]
Tested this with a throttled network connection, and got no luck in reproducing this. Noticed that the error in #3730 is actually for tag creation, just like @ApocalypticFish mentioned, and it's all inside a `IMvxAsyncCommand` so maybe MVExit will take care of this?

**Comment by heytherewill** [comment]
Given the current comments and my inability to reproduce, I'm closing this issue down
