### ISSUE TITLE
NullReferenceException in EditTimeEntryActivity.setupViews

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4926]
## 💥 Crash Report
This supposedly happens to a significant number of users on 1.13, when they open the Edit View.

### 👥 Impact
Current rollout: 5% (halted)
By now, occured `65` times to `43` users. 

### 🔗 Context
In 1.13, the Edit View has been rxfactored. This error has not been seen on any previous build (the excepting method hasn't existed before 1.13).

### 🛰 Link
[AppCenter details.](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/1586665989u/overview)

### 📝  Exception & Stack Trace
Unfortunatelly, this is all there is:
`System.NullReferenceException: Object reference not set to an instance of an object`

```cs
EditTimeEntryActivity.setupViews ()
EditTimeEntryActivity.OnCreate (Android.OS.Bundle bundle)
Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)
```

**Comment by kornelijepetak** [comment]
[A short analysis of possible NRE in the mentioned method] (https://github.com/toggl/mobileapp/compare/release/giskard-1.13-potassium...helper/setupViews?expand=1#diff-e5c31fbfe0fc01362c1196cf07cfdece)

**Comment by juanlaube** [comment]
@kornelijepetak I've been trying to reproduce this without success, and your analysis makes sense to me, also I couldn't find when the Prepare method is called (mvexit should solve this doubt).

Proposal: how about running `setupViews` only after the `Prepare` method finishes? We would need a new observable that emits at the very end of prepare and subscribe in the activity to execute setupViews.

**Comment by juanlaube** [comment]
Also removing myself so others can take a look. I will try my proposal tomorrow if there are no other ideas.

**Comment by kornelijepetak** [comment]
I'm reopening the issue. This still happens on `1.13.3`. It does look a bit better, but since not many users have switched yet, it might be a bias.

**Comment by kornelijepetak** [comment]
One thing we can note is that it usually happens rather quickly, except for a very small number of cases, when it takes longer. But for most part, the crash happens 2-3 seconds into the opening.

![image](https://user-images.githubusercontent.com/7033216/56495594-8786c680-64f6-11e9-8a0c-7a601b26f341.png)

**Comment by juanlaube** [comment]
We added a bunch of diagnostics in #4967 that can be removed since the bug is solved.

**Comment by juanlaube** [comment]
#4987 will take care of removing the diagnostics code, this can be closed now
