### ISSUE TITLE
App is not syncing

### ISSUE THREAD

**Issue by nidarasheed** [toggl/mobileapp#5419]
## 🐛 Bug Report
The app is not syncing, and it is using too much power. 
The app had to be restarted 3 times for it to sync, and it used 4.2% of battery in the process. 
From user "t’s a third place in chart of power consumption, after Android system and Skype (video call)." 
## Context
This is from a user who was facing sync issues on 1.14 and 1.15, and has now upgraded to 2.0 and is *still* facing issues.

Build/Branch: Giskard 2.0
Phone OS: Android 8.0.0
Phone model: MI 5s

## Expected behavior
The app should sync without needing to be restarted, and it should not use this much power. 

## To reproduce
N/A

## Suggestions
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22078723117)

**Comment by zdericnina** [comment]
another user facing syncing issues after updating to 2.0 (Phone model: Pixel 2; Platform and OS version: Android 9)

> The wheel just keeps spinning and nothing syncs.

[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22456768805)

**Comment by amulware** [comment]
The original description does not state the actual problem. 'not syncing' isn't very clear. Do time entries from the server not get pulled? Do local changes not get pushed? Is it merely that it displays the syncing spinner or claims that sync has failed but data actually syncs fine?

Please add answers to these questions, or I will close this issue. :)

**Comment by amulware** [comment]
Also, removing mentions of battery consumption, that's a separate issue, if an issue at all (it was discussed internally that it probably is not, so more data would be needed).

**Comment by amulware** [comment]
Assigning to project. Close this issue if no new information in the next week.

**Comment by nidarasheed** [comment]
Just saw this note. Have asked user for more information and will update here when I have it.

**Comment by VeljkoTN** [comment]
@amulware we got feedback from the user. They say that the app does sync but that it takes a long time to do it and they suspect that it drains the battery as well and that their phone even becomes noticeably hot, considering that power consumption is a different issue than syncing I'll post the users' feedback here: #5483

**Comment by lise-toggl** [comment]
@amulware a [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22638825727) where the new entries from the web get downloaded, but the ios app's entries don't get sent up, and a manual sync seems to freeze

**Comment by amulware** [comment]
The sync _seems_ to freeze? What exactly does that mean? If this is reproducable, could you ask the user to wait for 1-2 minutes, and tell us if sync does complete within that time?

It could be that it gets locked into a 1m delay where nothing will happen even though it looks like it's syncing.

**Comment by lise-toggl** [comment]
@amulware i believe he meant the syncing spinner stopped moving - but syncing seems to be working again after a reinstall so hopefully we won't hear back from him any more!

another [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22108857207) that came in today - i'll ask her to do that and report back :)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22608545789)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22456768805)
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/22673263606)

**Comment by lise-toggl** [comment]
@amulware we got a detailed answer from a user on a Pixel 2 running Android 9:

> Thanks for the quick reply, Lisa. I did as you asked: I pulled downwards to initiate a refresh, and then I didn't touch anything. The circle icon kept going.
> 
> After about 60 seconds, my screen automatically turned off, so I pressed my power button once on the Google Pixel 2 which interrupts the screen from entering power save mode. It remained on the Toggl app, and the circle icon kept going.
> 
> After another 60 seconds, my screen automatically turned off again, so I did the same thing to prevent it from entering power save mode. Once again, my phone remained on the Toggl app, and the circle icon kept going.
> 
> I repeatedly prevented my phone from entering power save mode. After about 5 minutes, the circle icon stopped spinning, and it remained static for about 2 minutes. I continued to prevent the phone from entering power save mode. After those 2 minutes, the circle icon continued to spin again.
> 
> After 12 minutes from the beginning of the refresh process, I gave up and exited the app again. The refresh was not successful. The circle was still spinning when I gave up.

does this help?

**Comment by lise-toggl** [comment]
a pattern noticed by one user

> I started this life of an international digital nomad and it seems to me that the problem occurs when I don't have cellular data enabled on my phone and just move between WiFi networks. I haven't done any rigorous testing yet, but it seems to me that if I start a job on my laptop one WiFi, the job gets started on the phone too, I see it running while I'm on the move. But if I then get to another location and stop the task on my laptop, it doesn't get stopped on the phone, even though both the laptop and the phone are connected to the same new WiFi. I sometimes find the task still running on the phone the next day. 
>
>What's even worse, is that there doesn't seem to be any way of getting out of this situation. If I stop it on the phone, it synces and I get 20 hours added to the long ago finished task on the laptop. If I instead delete it on the phone, it gets deleted from the laptop too. I had to stop using the app, and revert to simply writing the start/stop times down on a piece of paper, which was why I was thinking about writing you. So it seems to me that when the app loses the connection for a few hours while the task is running, the syncing fails and the task keeps on running. 
>
>An example of such a task was [REMOVED], which took about 6 hours. I started it on WiFi before I left, but when I stopped it after I came back, it just kept on running on the phone. I'll try to test it, watch the behavior closely and give you/your developers a more accurate report.

**Comment by amulware** [comment]
@lise-toggl Details here are fine. With regards to the last case: Did they try syncing manually? Different apps will always be out of sync a little bit if syncing does not complete, that's nothing new, and nothing we can prevent entirely.

**Comment by juanlaube** [comment]
I've read all the support cases linked here and there is no correlation between them. In some cases the problems were solved after updating the app from really old versions.
The only common pattern in a few cases is the slowness in sync, which is probably caused by the rate limit in the API and there's not much we can do. I noticed those users have a lot of time entries in the database though (+1500 in some cases), we will try to investigate if this is a reason for the slowness in a separate issue.

**Comment by egordorichev** [comment]
This issue still pops from time to time on newer versions of the Android app. I'm on the Beta program, and the sync been broken for ~2 weeks now. Hoping that it would be fixed in the next beta updates, but still kind of worried about loosing all the tracked data, since there is no way to export it from just the mobile app itself.
